// <auto-generated />
using System;
using EcoLogistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814100904_AddConducteur")]
    partial class AddConducteur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<string>("N_plaque")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Quantite_Npalette")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_perso");

                    b.ToTable("Conducteurs");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Donnees_perso", b =>
                {
                    b.Property<Guid>("Id_perso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date_licenciement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_localite")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_perso");

                    b.ToTable("Donnees_persos");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.Property<Guid>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id_user");

                    b.HasIndex("Id_perso");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });
#pragma warning restore 612, 618
        }
    }
}
