// <auto-generated />
using System;
using EcoLogistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826114925_CreateClientBlock")]
    partial class CreateClientBlock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.AdresseExploitation", b =>
                {
                    b.Property<int>("Id_adresse_exp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_adresse_exp"));

                    b.Property<Guid>("Id_client")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<string>("Nom_site")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id_adresse_exp");

                    b.HasIndex("Id_client");

                    b.HasIndex("Id_localite");

                    b.ToTable("AdressesExploitation");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.Client", b =>
                {
                    b.Property<Guid>("Id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Agrement_BE")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BE_entreprise")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enregistrement_BE")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<int?>("Id_siege")
                        .HasColumnType("int");

                    b.Property<Guid?>("Id_user")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom_entreprise")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("Numero_entreprise")
                        .HasColumnType("int");

                    b.Property<string>("Presentation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type_enregistrement")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_client");

                    b.HasIndex("Id_localite");

                    b.HasIndex("Id_siege");

                    b.HasIndex("Id_user");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.PersonneContact", b =>
                {
                    b.Property<int>("Id_contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_contact"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("Id_client")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id_contact");

                    b.HasIndex("Id_client");

                    b.HasIndex("Id_localite");

                    b.ToTable("PersonneContacts");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.SiegeSociale", b =>
                {
                    b.Property<int>("Id_siege")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_siege"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<string>("Raison_sociale")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Secteur_activite")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Site_internet")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id_siege");

                    b.HasIndex("Id_localite");

                    b.ToTable("SiegeSociales");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.CommuneBXL", b =>
                {
                    b.Property<int>("Id_commune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_commune"));

                    b.Property<string>("Commune_principale")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Nom_fr")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Nom_nl")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Sous_commune")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id_commune");

                    b.ToTable("CommuneBXLs");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Localite", b =>
                {
                    b.Property<int>("Id_localite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_localite"));

                    b.Property<string>("Code_postal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("Id_commune")
                        .HasColumnType("int");

                    b.Property<int?>("Id_pays")
                        .HasColumnType("int");

                    b.Property<string>("Nom_localite")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Province")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id_localite");

                    b.HasIndex("Id_commune");

                    b.HasIndex("Id_pays");

                    b.ToTable("Localites");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Pays", b =>
                {
                    b.Property<int>("Id_pays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_pays"));

                    b.Property<string>("Code_ISO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom_pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_pays");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.Property<int>("Id_conducteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_conducteur"));

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<string>("N_plaque")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Quantite_Npalette")
                        .HasColumnType("int");

                    b.HasKey("Id_conducteur");

                    b.HasIndex("Id_perso");

                    b.ToTable("Conducteurs");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Donnees_perso", b =>
                {
                    b.Property<Guid>("Id_perso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date_licenciement")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Poste")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_perso");

                    b.HasIndex("Id_localite");

                    b.ToTable("Donnees_persos");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.Property<Guid>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id_user");

                    b.HasIndex("Id_perso");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.AdresseExploitation", b =>
                {
                    b.HasOne("EcoLogistics.Models.ClientBlock.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.Navigation("Client");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.Client", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.HasOne("EcoLogistics.Models.ClientBlock.SiegeSociale", "SiegeSociale")
                        .WithMany()
                        .HasForeignKey("Id_siege");

                    b.HasOne("EcoLogistics.Models.UserBlock.User", "User")
                        .WithMany()
                        .HasForeignKey("Id_user");

                    b.Navigation("Localite");

                    b.Navigation("SiegeSociale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.PersonneContact", b =>
                {
                    b.HasOne("EcoLogistics.Models.ClientBlock.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.Navigation("Client");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("EcoLogistics.Models.ClientBlock.SiegeSociale", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Localite", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.CommuneBXL", "CommuneBXL")
                        .WithMany()
                        .HasForeignKey("Id_commune");

                    b.HasOne("EcoLogistics.Models.Geo.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("Id_pays");

                    b.Navigation("CommuneBXL");

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Donnees_perso", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });
#pragma warning restore 612, 618
        }
    }
}
