// <auto-generated />
using System;
using EcoLogistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820072940_UpdateDonneesPerso")]
    partial class UpdateDonneesPerso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoLogistics.Models.Geo.CommuneBXL", b =>
                {
                    b.Property<int>("Id_commune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_commune"));

                    b.Property<string>("Commune_principale")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Nom_fr")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Nom_nl")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Sous_commune")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id_commune");

                    b.ToTable("CommuneBXLS");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Localite", b =>
                {
                    b.Property<int>("Id_localite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_localite"));

                    b.Property<string>("Code_postal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("Id_commune")
                        .HasColumnType("int");

                    b.Property<int?>("Id_pays")
                        .HasColumnType("int");

                    b.Property<string>("Nom_localite")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Province")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id_localite");

                    b.HasIndex("Id_commune");

                    b.HasIndex("Id_pays");

                    b.ToTable("Localites");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Pays", b =>
                {
                    b.Property<int>("Id_pays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_pays"));

                    b.Property<string>("Code_ISO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom_pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_pays");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.Property<int>("Id_conducteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_conducteur"));

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<string>("N_plaque")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Quantite_Npalette")
                        .HasColumnType("int");

                    b.HasKey("Id_conducteur");

                    b.HasIndex("Id_perso");

                    b.ToTable("Conducteurs");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Donnees_perso", b =>
                {
                    b.Property<Guid>("Id_perso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date_licenciement")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_localite")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Poste")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_perso");

                    b.HasIndex("Id_localite");

                    b.ToTable("Donnees_persos");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.Property<Guid>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Id_perso")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id_user");

                    b.HasIndex("Id_perso");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoLogistics.Models.Geo.Localite", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.CommuneBXL", "CommuneBXL")
                        .WithMany()
                        .HasForeignKey("Id_commune");

                    b.HasOne("EcoLogistics.Models.Geo.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("Id_pays");

                    b.Navigation("CommuneBXL");

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Conducteur", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.Donnees_perso", b =>
                {
                    b.HasOne("EcoLogistics.Models.Geo.Localite", "Localite")
                        .WithMany()
                        .HasForeignKey("Id_localite");

                    b.Navigation("Localite");
                });

            modelBuilder.Entity("EcoLogistics.Models.UserBlock.User", b =>
                {
                    b.HasOne("EcoLogistics.Models.UserBlock.Donnees_perso", "Donnees_perso")
                        .WithMany()
                        .HasForeignKey("Id_perso");

                    b.Navigation("Donnees_perso");
                });
#pragma warning restore 612, 618
        }
    }
}
